# ===================================================================
#             Configuration File for NeuroOmics-Net
# ===================================================================

# -------------------------------------------------------------------
#                           DATA PATHS
# -------------------------------------------------------------------
DATA:
  METADATA_PATH: "data_processed/metadata.csv"
  SMR_PATH: "data_processed/smri"
  GENE_PATH: "data_processed/gene_expression"
  # CLASS_NAMES are used for labeling plots. Ensure the order matches the integer labels.
  CLASS_NAMES: ["No Impairment", "Very Mild Impairment", "Mild Impairment", "Moderate Impairment"] 

# -------------------------------------------------------------------
#                           TRAINING SETTINGS
# -------------------------------------------------------------------
TRAINING:
  DEVICE: "cuda"
  NUM_EPOCHS: 100
  BATCH_SIZE: 16
  LEARNING_RATE: 0.0001
  OPTIMIZER: "AdamW"
  WEIGHT_DECAY: 0.01
  NUM_CLASSES: 4
  SHUFFLE_DATA: True
  SET_SEED: 42

# -------------------------------------------------------------------
#                           MODEL ARCHITECTURE
# -------------------------------------------------------------------
MODEL:
  DROPOUT_RATE: 0.4
  HME:
    SMRI_EMBED_DIM: 256
    EEG_EMBED_DIM: 128
    GENE_EMBED_DIM: 128
  DPGL:
    GRAPH_HIDDEN_DIM: 64
  CAF:
    ATTENTION_DIM: 512

# -------------------------------------------------------------------
#                       INPUT DATA SPECIFICATIONS
# -------------------------------------------------------------------
INPUT_SPECS:
  SMRI_SHAPE: [96, 96]
  GENE_VECTOR_SIZE: 1000

# -------------------------------------------------------------------
#                         OUTPUT & LOGGING
# -------------------------------------------------------------------
OUTPUT:
  CHECKPOINT_DIR: "checkpoints/"
  LOGS_DIR: "logs/"
  PLOTS_DIR: "plots/"
  INTERPRET_DIR: "interpretability/"
  TRAINED_MODELS_DIR: "trained_models/"

# -------------------------------------------------------------------
#                       INTERPRETABILITY SETTINGS
# -------------------------------------------------------------------
INTERPRET:
  # The class index to generate saliency maps for.
  # 0: "No Impairment", 1: "Very Mild Impairment", 2: "Mild", 3: "Moderate"
  TARGET_CLASS_IDX: 3